require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const crypto = require('crypto');
const { Client, Environment, PaymentsApi } = require('square');

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// ---- Square client ------------------------------------------------------
const environment =
  process.env.SQUARE_ENVIRONMENT === 'production'
    ? Environment.Production
    : Environment.Sandbox;

const squareClient = new Client({
  token: process.env.SQUARE_ACCESS_TOKEN,
  environment,
});

const paymentsApi = new PaymentsApi(squareClient);

// Public config for the frontend (Application ID and Location ID are PUBLIC;
// the Access Token stays on the server only)
app.get('/api/config', (req, res) => {
  res.json({
    applicationId: process.env.SQUARE_APPLICATION_ID,
    locationId: process.env.SQUARE_LOCATION_ID,
    environment: process.env.SQUARE_ENVIRONMENT || 'sandbox',
  });
});

// ---- Product catalog -----------------------------------------------------
const products = require('./public/data/products.json');

app.get('/api/products', (req, res) => {
  res.json(products);
});

// ---- Checkout / Payment --------------------------------------------------
// Custom hat upcharges (mirrored in public/js/cart.js and checkout.js)
const PATCH_PRICES = {
  Embroidered: 2990,
  'Laser Engraved': 2390,
  'UV Printed Leatherette': 2690,
};
const TEXT_PRICE = 800;

function itemPriceCents(product, options) {
  // Custom hats: the total is FIXED by the chosen patch, regardless of base model
  if (options) {
    let price = PATCH_PRICES[options.patch] || 0;
    if (options.text && options.text.trim()) price += TEXT_PRICE;
    return price;
  }
  return product.price;
}

// Receives the cart ({id, quantity, options}[]) + the sourceId (card token generated by
// the Square Web Payments SDK in the browser) and creates the payment.
app.post('/api/checkout', async (req, res) => {
  try {
    const { cart, sourceId, buyerEmail } = req.body;

    if (!sourceId) {
      return res.status(400).json({ error: 'Card token (sourceId) missing.' });
    }
    if (!Array.isArray(cart) || cart.length === 0) {
      return res.status(400).json({ error: 'Your cart is empty.' });
    }

    // Recalculate the total ON THE SERVER from products.json — never trust a
    // total sent by the browser, it can be tampered with.
    let totalCents = 0;
    for (const item of cart) {
      const product = products.find((p) => p.id === item.id);
      if (!product) {
        return res.status(400).json({ error: `Invalid product: ${item.id}` });
      }
      const quantity = Math.max(1, parseInt(item.quantidade, 10) || 1);
      totalCents += itemPriceCents(product, item.options) * quantity;
    }

    if (totalCents <= 0) {
      return res.status(400).json({ error: 'Invalid order total.' });
    }

    const response = await paymentsApi.createPayment({
      sourceId,
      idempotencyKey: crypto.randomUUID(),
      amountMoney: {
        amount: BigInt(totalCents),
        currency: 'USD',
      },
      locationId: process.env.SQUARE_LOCATION_ID,
      buyerEmailAddress: buyerEmail || undefined,
    });

    const payment = response.payment;

    res.json({
      success: true,
      paymentId: payment.id,
      status: payment.status,
      receiptUrl: payment.receiptUrl,
    });
  } catch (err) {
    console.error('Checkout error:', err);
    const detail =
      err?.errors?.[0]?.detail || err?.message || 'Error processing payment.';
    res.status(500).json({ error: detail });
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`OAKTOPUS store running at http://localhost:${PORT}`);
  console.log(`Square environment: ${process.env.SQUARE_ENVIRONMENT || 'sandbox'}`);
});
